### ISSUE TITLE
ESLint error in bench.js

### ISSUE THREAD

**Issue by lucastheisen** [alexindigo/asynckit#46]
Ran across this while testing an npm patch:

```
Error: C:\Users\ltheisen\git\npm\test\tap\builtin-config\first\node_modules\npm\node_modules\request\node_modules\form-d
ata\node_modules\asynckit\bench.js line 1:
        Configuration for rule "no-console" is invalid:
        Severity should be one of the following: 0 = off, 1 = warning, 2 = error (you passed "off").
```

**Comment by alexindigo** [comment]
Hey,

Thanks for the report. But in this case your tool should ignore node_modules altogether, all sorts of weird stuff could be found there, and usually app developer has no control over it. :)
So only files developer directly responsible for are checked.

Asynckit kit uses different version of eslint, where no-console is pretty valid directive.

**Comment by lucastheisen** [comment]
@alexindigo , i agree, but its not my project... its _npm_...  A crazy condition where if the unit tests stopped without cleanup it left a temp directory (containing its node_modules for that test) which gets linted before it allows you to run the tests again.  That lint run would fail with the error above, so I just wanted to let you know.  

That said, i should have checked the version of eslint from npm, `2.2.0` (by way of `standard@6.0.8`).  Somewhere between that, and your version `2.9.0`, they added `off`, `warn`, and `error` as aliases to 0, 1, and 2...  Sorry to bug you unnecessarily :)

**Comment by alexindigo** [comment]
@lucastheisen No worries, thanks for bring it up.
I'm curious about that "npm" thing, do you mind to elaborate a bit more on your setup and what you run to see the error?

I'd assume each project would have it's own eslint configuration (or even something beyond eslint) and it shouldn't affect other projects. So if you hit that kind of thing, something strange is going on.

**Comment by lucastheisen** [comment]
Sure...  Basically, trying to submit a [pull request](https://github.com/npm/npm/pull/16213) to add [a new options for the version command](https://github.com/npm/npm/issues/11342#issuecomment-290778013).  In doing so, I modified one unit test and added another.  Their test suite is really large (as would be expected of a project of that magnitude), so when I attempted to `npm test`, it was taking forever.  So i <kbd>ctrl</kbd><kbd>c</kbd>'d it and ran specific tests `npm run tap -- "test/tap/version*"` to verifiy my test modifications were working.  But before I pushed my code to create the pull request, I wanted to verify the whole test suite (yeah, wait 30 minutes)...  But the tests failed immediately because it ran the linter before the tests (`standard`):
```
  "scripts": {
...
    "test": "standard && npm run test-tap",
...
  },
```
And the <kbd>ctrl</kbd><kbd>c</kbd> had left some of the test folders from the previous round of testing (their tests put the temp folders at `test/tap/<test_file_name_without_ext>/`) which included their own `node_modules` folders (testing `npm` itself).  Given that the temp folders are under a source code directory that _IS_ linted, everything under them is also linted and...  There you have it...  Make sense?

**Comment by alexindigo** [comment]
Ah, I see. Yeah broken state can drive one nuts. Thanks for following up. Good luck with the PR.
